#!/bin/bash

USERANME=$1
ACCESS_TOKEN=$2
CI_REGISTRY=$3
PROJECT=$4
NAME_UNIT_TEST_IMAGE=$5

docker login -u $USERNAME -p $ACCESS_TOKEN $CI_REGISTRY

docker build -t ${CI_REGISTRY}/${PROJECT}/${NAME_UNIT_TEST_IMAGE} . 

docker push ${CI_REGISTRY}/${PROJECT}/${NAME_UNIT_TEST_IMAGE}
