service_names:
  - "kubelet"
packages_to_install:
  - kubelet
  - kubeadm
  - kubectl
  - nfs-common
keys_to_add:
  - https://packages.cloud.google.com/apt/doc/apt-key.gpg
repos_to_add:
  - deb https://apt.kubernetes.io/ kubernetes-xenial main