- name: Add repo keys
  apt_key:
    url: "{{ item }}"
    state: present
  loop: "{{ keys_to_add }}"

- name: Add repos
  apt_repository:
    repo: "{{ item }}"
    state: present
  loop: "{{ repos_to_add }}"

- name: Installing "{{ packages_to_install }}" packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  loop: "{{ packages_to_install }}"

- name: Starting and enabling service
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  loop: "{{ service_names }}"

- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    append: yes
    groups: docker

- name: Rebbot
  reboot:
    reboot_timeout: 30

- name: Pause
  pause:
    seconds: 30